environment: dev
basedir: /home/dlink/stemsible
serverurl: localhost:5000

database:
   engine : mysql
   db     : dev_stemsible
   host   : localhost
   user   : stemsible
   passwd : redXnapper56
   dictcursor: True

logging:
   dir: /home/dlink/log
   filename: /home/dlink/log/stemsible.log
   level: DEBUG

sessions:
   dir: /data/stemsible/sessions
