environment: dev
baseurl: dev.stemsible.com
basedir: /home/dlink/stemsible
serverurl: localhost:5000

database:
   engine : mysql
   db     : dev_stemsible
   host   : localhost
   user   : dev_stemsible
   passwd : $STEM_DEV_DBPASS
   dictcursor: True

logging:
   dir: /home/dlink/log
   filename: /home/dlink/log/stemsible.log
   level: DEBUG

sessions:
   dir: /data/stemsible/dev-sessions

emails:
   name: Stemsible
   username: info@stemsible.com
   password: $STEMSIBLE_EMAIL_PASS
