environment: prod
baseurl: stemsible.com
basedir: /apps/stemsible
serverurl: localhost:5000

database:
   engine : mysql
   db     : stemsible
   host   : localhost
   user   : stemsible
   passwd : redXnapper56
   dictcursor: True

logging:
   dir: /var/log/stemsible
   filename: /var/log/stemsible/stemsible.log
   level: DEBUG

sessions:
   dir: /data/stemsible/sessions

emails:
   username: info@stemsible.com
   password: $STEMSIBLE_EMAIL_PASS
