environment: dev
baseurl: ukumar.stemsible.com
basedir: /home/ukumar/stemsible
serverurl: localhost:5000

database:
   engine : mysql
   db     : dev_stemsible
   host   : localhost
   user   : stemsible
   passwd : redXnapper56
   dictcursor: True

logging:
   dir: /home/ukumar/log
   filename: /home/ukumar/log/stemsible.log
   level: DEBUG

sessions:
   dir: /data/stemsible/sessions_ukumar

emails:
   username: info@stemsible.com
   password: $STEMSIBLE_EMAIL_PASS
